/**
 * Five mood-worlds, each matched to a real music genre and made to look
 * EXTREMELY different from the others — different background, shape, layout,
 * speed, symmetry and ink style — while all keeping the immersive close crop
 * that fills the frame.
 *
 *   music           — full ~20s genre track (public/audio/…)
 *   musicStartFrame — where to start the 3s slice (a hard cut mid-song)
 *   efOffset        — engine-frames skipped so we open mid-evolution
 */

// 20s track @ 60fps = 1200 frames; open the slice ~10s in (the middle).
const MID = 600;

export const MOODS = [
  {
    id: "calm",
    genre: "neoclassical strings",
    music: "audio/mood-calm.mp3",
    musicStartFrame: MID,
    efOffset: 220,
    // Slow, elegant electric-blue kaleido spiral, mint ramp. The user's ref.
    config: {
      layout: "spiral",
      shape: "circle",
      count: 115,
      size: 0.44,
      floor: 0.2,
      aspect: 1,
      roundness: 0,
      freq: 1.8,
      noise: 0,
      twist: 5.3,
      twirl: 0.8,
      velocity: 0.41,
      ampX: 1.15,
      ampY: 0.4,
      zoom: 2.79,
      offsetX: 0.47,
      offsetY: 0.75,
      rotate: 85,
      mirror: "off",
      kaleido: 3,
      orbit: 0.08,
      coil: 7,
      lineWidth: 0.7,
      fillAlpha: 1,
      strokeAlpha: 1,
      blend: "normal",
      trail: 0,
      seed: 0,
      colors: {
        bg: "#00019C",
        fill: "#0010FF",
        stroke: "#1D1D1D",
        ramp: ["#0010FF", "#B2FFDD", "#90FFCE"],
      },
    },
  },

  {
    id: "pop",
    genre: "synth-pop",
    music: "audio/mood-pop.mp3",
    musicStartFrame: MID,
    efOffset: 30,
    // LIGHT bg, bold-outlined candy rounded squares, 4-fold kaleido, bouncy.
    config: {
      layout: "ring",
      shape: "square",
      count: 60,
      size: 1.05,
      floor: 0.34,
      aspect: 1,
      roundness: 0.5,
      freq: 1,
      noise: 0,
      twist: 2.2,
      twirl: 0.45,
      velocity: 1.35,
      ampX: 0.95,
      ampY: 0.95,
      zoom: 1.5,
      offsetX: 0,
      offsetY: 0,
      rotate: 0,
      mirror: "off",
      kaleido: 4,
      orbit: 0.14,
      coil: 5,
      lineWidth: 1.4,
      fillAlpha: 1,
      strokeAlpha: 1,
      blend: "normal",
      trail: 0,
      seed: 7,
      colors: {
        bg: "#FDEEC8",
        fill: "#FF2D95",
        stroke: "#1D1D1D",
        ramp: ["#FF2D95", "#FFD400", "#00C2FF", "#7A5CFF"],
      },
    },
  },

  {
    id: "psych",
    genre: "psychedelic rock",
    music: "audio/mood-psych.mp3",
    musicStartFrame: MID,
    efOffset: 80,
    // Melting, glowing coils on deep indigo — trails + lighter blend + orbit.
    config: {
      layout: "ring",
      shape: "circle",
      count: 120,
      size: 1.15,
      floor: 0.15,
      aspect: 1.7,
      roundness: 0,
      freq: 1,
      noise: 0.1,
      twist: 3.6,
      twirl: 0.7,
      velocity: 1.1,
      ampX: 0.95,
      ampY: 0.95,
      zoom: 1.35,
      offsetX: 0,
      offsetY: 0,
      rotate: 0,
      mirror: "off",
      kaleido: 2,
      orbit: 0.5,
      coil: 13,
      lineWidth: 0.85,
      fillAlpha: 0.14,
      strokeAlpha: 0.85,
      blend: "lighter",
      trail: 0.8,
      seed: 3,
      colors: {
        bg: "#12002E",
        fill: "#FF2D95",
        stroke: "#FF7A00",
        ramp: ["#FF00A0", "#FF7A00", "#B14BFF", "#00FFC2"],
      },
    },
  },

  {
    id: "flamenco",
    genre: "flamenco guitar",
    music: "audio/mood-flamenco.mp3",
    musicStartFrame: MID,
    efOffset: 50,
    // Warm overlapping fan blades on deep wine — wave-x, mirrored, elongated.
    config: {
      layout: "wave-x",
      shape: "circle",
      count: 92,
      size: 1.5,
      floor: 0.06,
      aspect: 2.6,
      roundness: 0,
      freq: 2.1,
      noise: 0,
      twist: 6.6,
      twirl: 0.12,
      velocity: 1.0,
      ampX: 0.95,
      ampY: 1.15,
      zoom: 1.5,
      offsetX: 0,
      offsetY: 0,
      rotate: 8,
      mirror: "x",
      kaleido: 1,
      orbit: 0,
      coil: 6,
      lineWidth: 0.7,
      fillAlpha: 1,
      strokeAlpha: 1,
      blend: "normal",
      trail: 0,
      seed: 4,
      colors: {
        bg: "#2A0008",
        fill: "#E01E2B",
        stroke: "#1A0005",
        ramp: ["#E01E2B", "#FF6A00", "#FFC24B"],
      },
    },
  },

  {
    id: "dnb",
    genre: "drum & bass",
    music: "audio/mood-dnb.mp3",
    musicStartFrame: MID,
    efOffset: 0,
    // Acid strobe grid of hard triangles — matrix, max speed, jitter, screen.
    config: {
      layout: "matrix",
      shape: "triangle",
      count: 100,
      size: 0.78,
      floor: 0.4,
      aspect: 1,
      roundness: 0,
      freq: 1.2,
      noise: 0.45,
      twist: 6,
      twirl: 1,
      velocity: 2,
      ampX: 1.2,
      ampY: 1.2,
      zoom: 1.15,
      offsetX: 0,
      offsetY: 0,
      rotate: 0,
      mirror: "off",
      kaleido: 1,
      orbit: 0,
      coil: 6,
      lineWidth: 1,
      fillAlpha: 0.12,
      strokeAlpha: 0.95,
      blend: "screen",
      trail: 0.25,
      seed: 6,
      colors: {
        bg: "#050506",
        fill: "#B6FF00",
        stroke: "#CBFF3A",
        ramp: ["#B6FF00", "#FFFFFF", "#00E5FF"],
      },
    },
  },
];
